### PR TITLE
Add Foundation 4 for some basic styling

### PR DESCRIPTION
**Pull request by kristianfreeman**
Not sure if this project is still alive, but I added some styling for my own perusal through the calculator. Thought I would make it available in case you wanted it to have a bit of style on initial cloning.

Also, curious what your direction was on the project. I have another commit in the works to make it deployable: I was thinking of hosting it on Heroku for usage amongst my fellow Persona-playing friends, but if you'd like to host the _official_ version of it, I'll send another PR your way and you can host it. 

Let me know what you think - my email is on my Github profile if that works better. Cheers!

### CODE REVIEW

**Comment by arantius** [comment]
Could you consider referencing some existing CDN (e.g. http://www.jsdelivr.com/#!foundation) rather than adding it all to this repo?

I have it hosted: http://arantius.com/misc/persona-3-fes-fusion-calculator/
But it's static files; a gh-pages branch would probably work just as well.

**Comment by kristianfreeman** [comment]
I gave that CDN a shot but it's doing a number on the page: a lot of "unresponsive script" alerts. My computer isn't particularly slow – I think the combination of lots of JS processing and external CSS is causing some issues.

The commit becomes _a lot_ smaller, but I think at the expense of usability. I can push the change and you can give it a shot, but I'm not too fond of pushing code that will make things worse.

**Comment by arantius** [comment]
If you've already got it written, send it as a separate pull request and I can choose which to accept, thanks!

**Comment by kristianfreeman** [comment]
Alright, after a bit more testing, found out I had some browser settings that were causing some issues. It looks good and performs well! Let me know what you think.

BTW, on a non-code standpoint, this has been super useful in the last couple weeks :smile: know anything about Persona 4, i.e. the similarities in fusions?

**Comment by arantius** [comment]
Sorry it took me so long to get to this.  I finally checked it out and looked at it: I don't like it.  The spacing and sizes of lots of things, ick.  My primary use case for this was on an android tablet, and this version would waste a huge chunk of the screen with the filter/input/clear boxes each on their own line, and the really giant header link (my back button works fine ...).

I added a LICENSE file to make this officially open source, feel free to fork and use your own version as you see fit.

And no: I haven't played persona 4 at all.

**Pull request closed without merging**
